# fly.toml app configuration file generated for listen-kit on 2025-01-28T12:38:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'listen-kit'
primary_region = 'sfo'

[build]

[env]
PORT = '6969'

[http_service]
internal_port = 6969
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
