steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/listen-sol-prod/listen-adapter:$COMMIT_SHA',
      '-t', 'gcr.io/listen-sol-prod/listen-adapter:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/listen-sol-prod/listen-adapter:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/listen-sol-prod/listen-adapter:latest']

images:
  - 'gcr.io/listen-sol-prod/listen-adapter:$COMMIT_SHA'
  - 'gcr.io/listen-sol-prod/listen-adapter:latest'

timeout: '1800s' 