apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: listen-data-service
data:
  redis.conf: |
    dir /data
    dbfilename dump.rdb
    save 900 1
    save 300 10
    save 60 10000
    appendonly no
    maxmemory 1536mb
    maxmemory-policy allkeys-lru
    io-threads 2
    io-threads-do-reads yes
    save ""
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: listen-data-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: listen-data-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: listen-data-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data 